/**
 * Export Service
 * Handles PDF, Markdown, and Salesforce Knowledge exports
 */

import { marked } from 'marked';

// ============================================
// TYPES
// ============================================

interface NarrativeExportData {
    id: string;
    title: string;
    status: string;
    createdAt: Date;
    updatedAt: Date;
    revisions: {
        hypothesis: string;
        confidence: number;
        authorId: string;
        timestamp: Date;
        evidence: unknown[];
        sources: unknown[];
    }[];
    collaborators: string[];
    tags: string[];
}

interface ExportResult {
    format: 'pdf' | 'markdown' | 'salesforce';
    content?: string;
    buffer?: Buffer;
    downloadUrl?: string;
}

// ============================================
// SERVICE
// ============================================

class ExportService {
    /**
     * Export narrative to Markdown format
     */
    async toMarkdown(narrative: NarrativeExportData): Promise<ExportResult> {
        const lines: string[] = [];

        // Header
        lines.push(`# ${narrative.title}\n`);
        lines.push(`**Status:** ${narrative.status}`);
        lines.push(`**Created:** ${narrative.createdAt.toLocaleDateString()}`);
        lines.push(`**Last Updated:** ${narrative.updatedAt.toLocaleDateString()}`);
        lines.push(`**Tags:** ${narrative.tags.join(', ') || 'None'}`);
        lines.push('');

        // Revisions
        lines.push('## Revision History\n');

        if (narrative.revisions.length === 0) {
            lines.push('*No revisions yet*\n');
        } else {
            for (const revision of narrative.revisions) {
                lines.push(`### ${revision.timestamp.toLocaleDateString()} - ${revision.timestamp.toLocaleTimeString()}\n`);
                lines.push(`**Hypothesis:** ${revision.hypothesis}\n`);
                lines.push(`**Confidence:** ${Math.round(revision.confidence * 100)}%\n`);

                if (revision.sources.length > 0) {
                    lines.push('**Sources:**');
                    lines.push('');
                    for (const source of revision.sources as any[]) {
                        lines.push(`- ${source.name || source}`);
                    }
                    lines.push('');
                }

                lines.push('---\n');
            }
        }

        // Footer
        lines.push('\n---');
        lines.push(`*Generated by Insight Weaver on ${new Date().toISOString()}*`);

        const content = lines.join('\n');

        return {
            format: 'markdown',
            content,
        };
    }

    /**
     * Export narrative to PDF format
     */
    async toPDF(narrative: NarrativeExportData): Promise<ExportResult> {
        // In production, use PDFKit or Puppeteer
        // For now, generate a placeholder

        const markdown = await this.toMarkdown(narrative);

        // Convert Markdown to HTML
        const html = marked(markdown.content || '');

        // In production:
        // const PDFDocument = require('pdfkit');
        // const doc = new PDFDocument();
        // ... generate PDF

        console.log(`[Export] Generated PDF for narrative: ${narrative.id}`);

        return {
            format: 'pdf',
            buffer: Buffer.from(`PDF content for: ${narrative.title}`),
            downloadUrl: `/api/v1/narratives/${narrative.id}/download?format=pdf`,
        };
    }

    /**
     * Export narrative to Salesforce Knowledge
     */
    async toSalesforceKnowledge(narrative: NarrativeExportData): Promise<ExportResult> {
        // In production, create Salesforce Knowledge article via API

        const markdown = await this.toMarkdown(narrative);

        console.log(`[Export] Published to Salesforce Knowledge: ${narrative.id}`);

        return {
            format: 'salesforce',
            content: markdown.content,
            downloadUrl: `https://salesforce.example.com/knowledge/${narrative.id}`,
        };
    }

    /**
     * Export narrative to specified format
     */
    async export(
        narrative: NarrativeExportData,
        format: 'pdf' | 'markdown' | 'salesforce'
    ): Promise<ExportResult> {
        switch (format) {
            case 'markdown':
                return this.toMarkdown(narrative);
            case 'pdf':
                return this.toPDF(narrative);
            case 'salesforce':
                return this.toSalesforceKnowledge(narrative);
            default:
                throw new Error(`Unsupported export format: ${format}`);
        }
    }

    /**
     * Capture visualization screenshot (placeholder)
     */
    async captureVisualization(vizUrl: string): Promise<Buffer> {
        // In production, use Puppeteer
        // const browser = await puppeteer.launch();
        // const page = await browser.newPage();
        // await page.goto(vizUrl);
        // const screenshot = await page.screenshot();
        // await browser.close();

        console.log(`[Export] Captured visualization: ${vizUrl}`);

        return Buffer.from('screenshot_placeholder');
    }
}

export const exportService = new ExportService();
