/**
 * Export Service
 * Handles PDF, Markdown, and Salesforce Knowledge exports
 */

import { marked } from 'marked';

// ============================================
// TYPES
// ============================================

interface NarrativeExportData {
    id: string;
    title: string;
    status: string;
    createdAt: Date;
    updatedAt: Date;
    revisions: {
        hypothesis: string;
        confidence: number;
        authorId: string;
        timestamp: Date;
        evidence: unknown[];
        sources: unknown[];
    }[];
    collaborators: string[];
    tags: string[];
}

interface ExportResult {
    format: 'pdf' | 'markdown' | 'salesforce';
    content?: string;
    buffer?: Buffer;
    downloadUrl?: string;
}

// ============================================
// SERVICE
// ============================================

class ExportService {
    /**
     * Export narrative to Markdown format
     */
    async toMarkdown(narrative: NarrativeExportData): Promise<ExportResult> {
        const lines: string[] = [];

        // Header
        lines.push(`# ${narrative.title}\n`);
        lines.push(`**Status:** ${narrative.status}`);
        lines.push(`**Created:** ${narrative.createdAt.toLocaleDateString()}`);
        lines.push(`**Last Updated:** ${narrative.updatedAt.toLocaleDateString()}`);
        lines.push(`**Tags:** ${narrative.tags.join(', ') || 'None'}`);
        lines.push('');

        // Revisions
        lines.push('## Revision History\n');

        if (narrative.revisions.length === 0) {
            lines.push('*No revisions yet*\n');
        } else {
            for (const revision of narrative.revisions) {
                lines.push(`### ${revision.timestamp.toLocaleDateString()} - ${revision.timestamp.toLocaleTimeString()}\n`);
                lines.push(`**Hypothesis:** ${revision.hypothesis}\n`);
                lines.push(`**Confidence:** ${Math.round(revision.confidence * 100)}%\n`);

                if (revision.sources.length > 0) {
                    lines.push('**Sources:**');
                    lines.push('');
                    for (const source of revision.sources as any[]) {
                        lines.push(`- ${source.name || source}`);
                    }
                    lines.push('');
                }

                lines.push('---\n');
            }
        }

        // Footer
        lines.push('\n---');
        lines.push(`*Generated by Insight Weaver on ${new Date().toISOString()}*`);

        const content = lines.join('\n');

        return {
            format: 'markdown',
            content,
        };
    }

    /**
     * Export narrative to PDF format
     */
    async toPDF(narrative: NarrativeExportData): Promise<ExportResult> {
        try {
            const PDFDocument = (await import('pdfkit')).default;
            const doc = new PDFDocument();
            const chunks: any[] = [];

            return new Promise((resolve, reject) => {
                doc.on('data', (chunk) => chunks.push(chunk));
                doc.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    resolve({
                        format: 'pdf',
                        buffer,
                        downloadUrl: `/api/v1/narratives/${narrative.id}/download?format=pdf`,
                    });
                });
                doc.on('error', (err) => {
                    console.error('[Export] PDF generation error:', err);
                    reject(err);
                });

                // --- Generate PDF Content ---
                doc.font('Helvetica');
                doc.fillColor('black');

                doc.fontSize(25).text('Insight Weaver — Narrative Report', { align: 'center' });
                doc.moveDown();

                doc.fontSize(18).text(narrative.title || 'Untitled Narrative');
                doc.fontSize(12).text(`Status: ${(narrative.status || 'draft').toUpperCase()}`, { continued: true });
                doc.text(` | Updated: ${new Date(narrative.updatedAt || Date.now()).toLocaleDateString()}`, { align: 'right' });
                doc.moveDown();

                doc.fontSize(14).text('Executive Summary', { underline: true });
                doc.fontSize(12).text(narrative.revisions?.[0]?.hypothesis || 'No active hypothesis.', { oblique: true });
                doc.moveDown();

                doc.fontSize(14).text('Revision History', { underline: true });
                doc.moveDown(0.5);

                if (narrative.revisions && narrative.revisions.length > 0) {
                    for (const rev of narrative.revisions) {
                        doc.fontSize(10).fillColor('black').text(`${new Date(rev.timestamp).toLocaleDateString()} — ${rev.hypothesis}`);
                        doc.fontSize(8).fillColor('gray').text(`Confidence: ${Math.round((rev.confidence || 0) * 100)}% | Author: ${rev.authorId}`);
                        doc.moveDown(0.5);
                    }
                } else {
                    doc.fontSize(10).fillColor('gray').text('No revision history available.');
                }

                doc.moveDown();
                doc.fontSize(8).fillColor('gray').text('Generated by Insight Weaver AI Librarian', { align: 'center' });

                doc.end();
            });
        } catch (error) {
            // Fallback: If PDF generation fails (missing native dependencies), return markdown as PDF
            console.error('[Export] PDF library error, falling back to text format:', error);
            const markdown = await this.toMarkdown(narrative);
            return {
                format: 'pdf',
                content: markdown.content,
                downloadUrl: `/api/v1/narratives/${narrative.id}/download?format=markdown`,
            };
        }
    }

    /**
     * Export narrative to Salesforce Knowledge
     */
    async toSalesforceKnowledge(narrative: NarrativeExportData): Promise<ExportResult> {
        // In production, create Salesforce Knowledge article via API

        const markdown = await this.toMarkdown(narrative);

        console.log(`[Export] Published to Salesforce Knowledge: ${narrative.id}`);

        return {
            format: 'salesforce',
            content: markdown.content,
            downloadUrl: `https://salesforce.example.com/knowledge/${narrative.id}`,
        };
    }

    /**
     * Export narrative to specified format
     */
    async export(
        narrative: NarrativeExportData,
        format: 'pdf' | 'markdown' | 'salesforce'
    ): Promise<ExportResult> {
        switch (format) {
            case 'markdown':
                return this.toMarkdown(narrative);
            case 'pdf':
                return this.toPDF(narrative);
            case 'salesforce':
                return this.toSalesforceKnowledge(narrative);
            default:
                throw new Error(`Unsupported export format: ${format}`);
        }
    }

    /**
     * Capture visualization screenshot (placeholder)
     */
    async captureVisualization(vizUrl: string): Promise<Buffer> {
        // In production, use Puppeteer
        // const browser = await puppeteer.launch();
        // const page = await browser.newPage();
        // await page.goto(vizUrl);
        // const screenshot = await page.screenshot();
        // await browser.close();

        console.log(`[Export] Captured visualization: ${vizUrl}`);

        return Buffer.from('screenshot_placeholder');
    }
}

export const exportService = new ExportService();
